app:
  hosts:
    appserver:
      ansible_host: 10.132.15.213
db:
  hosts:
    dbserver:
      ansible_host: 10.132.15.211

ansible:
  hosts:
    workstation:
      ansible_host: 10.132.0.59

      
